### ISSUE TITLE
NAPS does not detect my scaner

### ISSUE THREAD

**Issue by Papipio** [cyanfish/naps2#53]
Bonjour,

I use Mageia Linux 8.
I can use my scanner with xsane, but I can't select my scanner with NAPS. The only scanner available is my webcam.
Why my scanner is not available ?

Pierre

**Comment by cyanfish** [comment]
What scanner model are you using?

Also, what SANE backend does it use? You can find out by running `scanimage -L`; for example, if it shows `device 'airscan:abc'`, that uses the airscan backend.

**Comment by Papipio** [comment]
Bonjour,

Thank you for your answer.
My scanner is the one of a Lexmark CX510de multifunction printer.

[papipio@localhost ~]$ scanimage -L
device `lexmark_nscan:libusb/001/023' is a Lexmark Lexmark CX510de Scanner
device `lexmark_nscan:libnet/SPECIFY_DEVICE' is a Lexmark Network Scanner
device `v4l:/dev/video0' is a Noname UVC Camera (046d:0805) virtual device
[papipio@localhost ~]$ 

With NAPS, only the 3rd device (UVC Camera) is available. I can get my photo on the display !

Pierre

**Comment by Vraiment** [comment]
I'm having the same problem with a brother DS-640:

```
> scanimage -L
device `brother5:bus4;dev1' is a Brother DS-640 USB scanner
```

**Comment by cyanfish** [comment]
I've added deb/rpm installers in [7.0b5](https://www.naps2.com/download) that should fix this issue (the problem is that with Flatpak the third-party drivers aren't available in the sandbox).

**Comment by rambo919** [comment]
> I've added deb/rpm installers in [7.0b5](https://www.naps2.com/download) that should fix this issue (the problem is that with Flatpak the third-party drivers aren't available in the sandbox).

This can be remedied with something like Flatseal but I don't know which option to use.

**Comment by cyanfish** [comment]
@rambo919 The problem isn't permissions, it's the structure of the Flatpak sandbox.

e.g. brscan5 is hard-coded to look for certain config files in /etc (IIRC), but in a Flatpak that's a fully read-only mount that belongs to the runtime. The NAPS2 Flatpak app code is mounted at /app, nowhere else. And even if you gave permissions to /etc on the host, it would actually get mounted under /var somewhere.

For open source drivers this is solvable (e.g. I might start bundling hplip at some point), but it's not solvable in general since we can't control what hard-coded paths closed-source drivers might depend on.
